In [2]:
import torch

In [3]:
# simple operation rehash
u = torch.tensor([2, 4])
v = torch.tensor([1, 4])
w = u * v
print(w)
print(w.shape)
print(w.ndim)

tensor([ 2, 16])
torch.Size([2])
1


In [4]:
# broadcasting rules 
a =     torch.ones(4, 3, 2)
a2 = torch.rand(   3, 2)
b = a * a2 # 3rd & 2nd dims identical to a, dim 1 absent
print(a)
print(a2)
print(b)

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])
tensor([[0.6671, 0.1449],
        [0.2843, 0.7691],
        [0.7278, 0.6361]])
tensor([[[0.6671, 0.1449],
         [0.2843, 0.7691],
         [0.7278, 0.6361]],

        [[0.6671, 0.1449],
         [0.2843, 0.7691],
         [0.7278, 0.6361]],

        [[0.6671, 0.1449],
         [0.2843, 0.7691],
         [0.7278, 0.6361]],

        [[0.6671, 0.1449],
         [0.2843, 0.7691],
         [0.7278, 0.6361]]])


In [5]:
c = a * torch.rand(   3, 1) # 3rd dim = 1, 2nd dim identical to a
print(c)

tensor([[[0.7302, 0.7302],
         [0.2413, 0.2413],
         [0.3209, 0.3209]],

        [[0.7302, 0.7302],
         [0.2413, 0.2413],
         [0.3209, 0.3209]],

        [[0.7302, 0.7302],
         [0.2413, 0.2413],
         [0.3209, 0.3209]],

        [[0.7302, 0.7302],
         [0.2413, 0.2413],
         [0.3209, 0.3209]]])


In [6]:
d = a * torch.rand(   1, 2) # 3rd dim identical to a, 2nd dim = 1
print(d)

tensor([[[0.0936, 0.9268],
         [0.0936, 0.9268],
         [0.0936, 0.9268]],

        [[0.0936, 0.9268],
         [0.0936, 0.9268],
         [0.0936, 0.9268]],

        [[0.0936, 0.9268],
         [0.0936, 0.9268],
         [0.0936, 0.9268]],

        [[0.0936, 0.9268],
         [0.0936, 0.9268],
         [0.0936, 0.9268]]])


In [11]:
# switch between ndarrays and PyTorch tensors
import numpy as np
numpy_array = np.ones((2, 3),dtype=int)
print(numpy_array)

pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

[[1 1 1]
 [1 1 1]]
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [19]:
# reverse example of converting from PyTorch tensor into ndarray
pytorch_rand = torch.rand(2, 3)
print(pytorch_rand)

numpy_rand = pytorch_rand.numpy()
print(numpy_rand)

tensor([[0.4111, 0.0874, 0.6247],
        [0.6761, 0.6112, 0.7817]])
[[0.41109467 0.0873512  0.624653  ]
 [0.67608976 0.61122954 0.78165585]]


In [9]:
# using the same underlying memory
numpy_array[1, 1] = 23
print(pytorch_tensor)

pytorch_rand[1, 1] = 17
print(numpy_rand)

tensor([[ 1.,  1.,  1.],
        [ 1., 23.,  1.]], dtype=torch.float64)
[[ 0.82105994  0.7738307   0.59401256]
 [ 0.35285002 17.          0.8489097 ]]


In [12]:
print(numpy_rand.shape)
print(numpy_rand.ndim)

(2, 3)
2


In [13]:
import numpy as np
numpy_array = np.ones((2, 3),dtype=int)
print(numpy_array)


[[1 1 1]
 [1 1 1]]


In [14]:
# using the same underlying memory
numpy_array[1, 1] = 23

In [17]:
print(numpy_array)

[[ 1  1  1]
 [ 1 23  1]]
tensor([[1, 1, 1],
        [1, 1, 1]], dtype=torch.int32)


In [18]:
pytorch_tensor = torch.from_numpy(numpy_array)
print(pytorch_tensor)

tensor([[ 1,  1,  1],
        [ 1, 23,  1]], dtype=torch.int32)


In [20]:
pytorch_rand[1, 1] = 17
print(numpy_rand)

[[ 0.41109467  0.0873512   0.624653  ]
 [ 0.67608976 17.          0.78165585]]


In [26]:
pytorch_rand = torch.rand(2,3)

In [27]:
print(pytorch_rand)

tensor([[0.5879, 0.7492, 0.4975],
        [0.8377, 0.0698, 0.5016]])


In [30]:
print(pytorch_rand)

tensor([[0.5879, 0.7492, 0.4975],
        [0.8377, 0.0698, 0.5016]])


In [28]:
rand_numpy=pytorch_rand.numpy()

In [29]:
print(rand_numpy)

[[0.5879215 0.7491546 0.4975205]
 [0.8377004 0.0697549 0.5016138]]


In [31]:
pytorch_rand[1,1]=3
print(rand_numpy)

[[0.5879215 0.7491546 0.4975205]
 [0.8377004 3.        0.5016138]]
